name: Zip and Publish

on:
  push

jobs:
  zip-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate commit hash
        run: echo "TAG_NAME=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Zip all matching directories together
        run: |
          zip -r all_directories.zip etca_* noc_* 2>/dev/null || echo "No matching directories found."

      - name: Upload zipped archive
        uses: actions/upload-artifact@v4
        with:
          name: zipped-directories
          path: "all_directories.zip"
          retention-days: 7

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: "all_directories.zip"
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
